# Generated by Django 2.2 on 2023-04-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230418_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
